name: Deploy Next.js Static Export

on:
  push:
    branches:
      - main   # jalan setiap push ke branch main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build & Export Next.js (static export)
        run:  npm run build

      - name: Deploy to gh-pages branch
        run: |
          git checkout gh-pages || git checkout -b gh-pages
          git config user.name "adrianfathurs"
          git config user.email "fatursetiawan80@gmail.com"
          git pull origin main
          git push origin gh-pages
